export const abi = [
  {
    type: 'event',
    anonymous: false,
    name: 'TaskCreated',
    inputs: [
      { type: 'uint256', name: 'taskId', indexed: true },
      { type: 'address', name: 'depositor', indexed: true },
      { type: 'string', name: 'modelHash', indexed: false },
      { type: 'string', name: 'datasetHash', indexed: false },
      { type: 'uint256', name: 'numChunks', indexed: false },
      { type: 'uint256', name: 'totalReward', indexed: false },
    ],
  },
  {
    type: 'event',
    anonymous: false,
    name: 'WeightsSubmitted',
    inputs: [
      { type: 'uint256', name: 'taskId', indexed: true },
      { type: 'address', name: 'trainer', indexed: true },
      { type: 'string', name: 'weightsHash', indexed: false },
      { type: 'uint256', name: 'rewardAmount', indexed: false },
      { type: 'uint256', name: 'remainingChunks', indexed: false },
    ],
  },
  {
    type: 'event',
    anonymous: false,
    name: 'Withdrawn',
    inputs: [
      { type: 'address', name: 'who', indexed: true },
      { type: 'uint256', name: 'amount', indexed: false },
    ],
  },
  { type: 'fallback', stateMutability: 'payable' },
  {
    type: 'function',
    name: 'cancelTask',
    constant: false,
    payable: false,
    inputs: [{ type: 'uint256', name: 'taskId' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'createTask',
    constant: false,
    stateMutability: 'payable',
    payable: true,
    inputs: [
      { type: 'string', name: 'modelHash' },
      { type: 'string', name: 'datasetHash' },
      { type: 'uint256', name: 'numChunks' },
    ],
    outputs: [{ type: 'uint256', name: '' }],
  },
  {
    type: 'function',
    name: 'hasSubmitted',
    constant: true,
    stateMutability: 'view',
    payable: false,
    inputs: [
      { type: 'uint256', name: '' },
      { type: 'address', name: '' },
    ],
    outputs: [{ type: 'bool', name: '' }],
  },
  {
    type: 'function',
    name: 'pendingWithdrawals',
    constant: true,
    stateMutability: 'view',
    payable: false,
    inputs: [{ type: 'address', name: '' }],
    outputs: [{ type: 'uint256', name: '' }],
  },
  {
    type: 'function',
    name: 'setPendingWithdrawal',
    constant: false,
    payable: false,
    inputs: [
      { type: 'address', name: '_address' },
      { type: 'uint256', name: '_amount' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'submitWeights',
    constant: false,
    payable: false,
    inputs: [
      { type: 'uint256', name: 'taskId' },
      { type: 'string', name: 'weightsHash' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'taskCount',
    constant: true,
    stateMutability: 'view',
    payable: false,
    inputs: [],
    outputs: [{ type: 'uint256', name: '' }],
  },
  {
    type: 'function',
    name: 'tasks',
    constant: true,
    stateMutability: 'view',
    payable: false,
    inputs: [{ type: 'uint256', name: '' }],
    outputs: [
      { type: 'address', name: 'depositor' },
      { type: 'string', name: 'modelHash' },
      { type: 'string', name: 'datasetHash' },
      { type: 'uint256', name: 'numChunks' },
      { type: 'uint256', name: 'remainingChunks' },
      { type: 'uint256', name: 'perChunkReward' },
      { type: 'bool', name: 'exists' },
    ],
  },
  {
    type: 'function',
    name: 'withdrawPending',
    constant: false,
    payable: false,
    inputs: [],
    outputs: [],
  },
  { type: 'receive', stateMutability: 'payable' },
];
