export const abi = [
  {
    type: 'constructor',
    stateMutability: 'undefined',
    payable: false,
    inputs: [],
  },
  {
    type: 'event',
    anonymous: false,
    name: 'TaskCompleted',
    inputs: [{ type: 'uint256', name: 'taskId', indexed: true }],
  },
  {
    type: 'event',
    anonymous: false,
    name: 'TaskCreated',
    inputs: [
      { type: 'uint256', name: 'taskId', indexed: true },
      { type: 'address', name: 'depositor', indexed: true },
      { type: 'string', name: 'modelUrl', indexed: false },
      { type: 'string', name: 'datasetUrl', indexed: false },
      { type: 'uint256', name: 'numChunks', indexed: false },
      { type: 'uint256', name: 'totalReward', indexed: false },
    ],
  },
  {
    type: 'event',
    anonymous: false,
    name: 'WeightsSubmitted',
    inputs: [
      { type: 'uint256', name: 'taskId', indexed: true },
      { type: 'address', name: 'trainer', indexed: true },
      { type: 'string', name: 'weight_hash_1', indexed: false },
      { type: 'string', name: 'weight_hash_2', indexed: false },
      { type: 'string', name: 'weight_hash_3', indexed: false },
      { type: 'uint256', name: 'rewardAmount', indexed: false },
      { type: 'uint256', name: 'remainingChunks', indexed: false },
    ],
  },
  {
    type: 'event',
    anonymous: false,
    name: 'Whitelisted',
    inputs: [
      { type: 'address', name: 'account', indexed: true },
      { type: 'bool', name: 'status', indexed: false },
    ],
  },
  {
    type: 'event',
    anonymous: false,
    name: 'Withdrawn',
    inputs: [
      { type: 'address', name: 'who', indexed: true },
      { type: 'uint256', name: 'amount', indexed: false },
    ],
  },
  { type: 'fallback', stateMutability: 'payable' },
  {
    type: 'function',
    name: 'addToWhitelist',
    constant: false,
    payable: false,
    inputs: [{ type: 'address', name: '_account' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'cancelTask',
    constant: false,
    payable: false,
    inputs: [{ type: 'uint256', name: 'taskId' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'count',
    constant: true,
    stateMutability: 'view',
    payable: false,
    inputs: [],
    outputs: [{ type: 'uint256', name: '' }],
  },
  {
    type: 'function',
    name: 'createTask',
    constant: false,
    stateMutability: 'payable',
    payable: true,
    inputs: [
      { type: 'string', name: 'modelUrl' },
      { type: 'string', name: 'datasetUrl' },
      { type: 'uint256', name: 'numChunks' },
    ],
    outputs: [{ type: 'uint256', name: '' }],
  },
  {
    type: 'function',
    name: 'getCount',
    constant: true,
    stateMutability: 'view',
    payable: false,
    inputs: [],
    outputs: [{ type: 'uint256', name: '' }],
  },
  {
    type: 'function',
    name: 'getTaskCounts',
    constant: true,
    stateMutability: 'view',
    payable: false,
    inputs: [],
    outputs: [{ type: 'uint256[]', name: '' }],
  },
  {
    type: 'function',
    name: 'getTaskId',
    constant: true,
    stateMutability: 'view',
    payable: false,
    inputs: [],
    outputs: [{ type: 'uint256', name: '' }],
  },
  {
    type: 'function',
    name: 'incrementCount',
    constant: false,
    payable: false,
    inputs: [],
    outputs: [],
  },
  {
    type: 'function',
    name: 'isWhitelisted',
    constant: true,
    stateMutability: 'view',
    payable: false,
    inputs: [{ type: 'address', name: '_account' }],
    outputs: [{ type: 'bool', name: '' }],
  },
  {
    type: 'function',
    name: 'owner',
    constant: true,
    stateMutability: 'view',
    payable: false,
    inputs: [],
    outputs: [{ type: 'address', name: '' }],
  },
  {
    type: 'function',
    name: 'pendingWithdrawals',
    constant: true,
    stateMutability: 'view',
    payable: false,
    inputs: [{ type: 'address', name: '' }],
    outputs: [{ type: 'uint256', name: '' }],
  },
  {
    type: 'function',
    name: 'removeFromWhitelist',
    constant: false,
    payable: false,
    inputs: [{ type: 'address', name: '_account' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'setPendingWithdrawal',
    constant: false,
    payable: false,
    inputs: [
      { type: 'address', name: '_address' },
      { type: 'uint256', name: '_amount' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'submitWeights',
    constant: false,
    payable: false,
    inputs: [
      { type: 'uint256', name: 'taskId' },
      { type: 'string', name: 'weightsHash' },
    ],
    outputs: [],
  },
  {
    type: 'function',
    name: 'taskCount',
    constant: true,
    stateMutability: 'view',
    payable: false,
    inputs: [],
    outputs: [{ type: 'uint256', name: '' }],
  },
  {
    type: 'function',
    name: 'taskCounts',
    constant: true,
    stateMutability: 'view',
    payable: false,
    inputs: [{ type: 'uint256', name: '' }],
    outputs: [{ type: 'uint256', name: '' }],
  },
  {
    type: 'function',
    name: 'taskExists',
    constant: true,
    stateMutability: 'view',
    payable: false,
    inputs: [{ type: 'uint256', name: 'taskId' }],
    outputs: [{ type: 'bool', name: '' }],
  },
  {
    type: 'function',
    name: 'taskWeights',
    constant: true,
    stateMutability: 'view',
    payable: false,
    inputs: [
      { type: 'uint256', name: '' },
      { type: 'uint256', name: '' },
    ],
    outputs: [{ type: 'string', name: '' }],
  },
  {
    type: 'function',
    name: 'tasks',
    constant: true,
    stateMutability: 'view',
    payable: false,
    inputs: [{ type: 'uint256', name: '' }],
    outputs: [
      { type: 'address', name: 'depositor' },
      { type: 'string', name: 'modelUrl' },
      { type: 'string', name: 'datasetUrl' },
      { type: 'uint256', name: 'numChunks' },
      { type: 'uint256', name: 'remainingChunks' },
      { type: 'uint256', name: 'perChunkReward' },
      { type: 'bool', name: 'exists' },
    ],
  },
  {
    type: 'function',
    name: 'whitelist',
    constant: true,
    stateMutability: 'view',
    payable: false,
    inputs: [{ type: 'address', name: '' }],
    outputs: [{ type: 'bool', name: '' }],
  },
  {
    type: 'function',
    name: 'withdrawPending',
    constant: false,
    payable: false,
    inputs: [],
    outputs: [],
  },
  { type: 'receive', stateMutability: 'payable' },
];
