/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { FederatedTrainingReward } from './FederatedTrainingReward.js';
export * as factories from './factories/index.js';
export { FederatedTrainingReward__factory } from './factories/FederatedTrainingReward__factory.js';